### ISSUE TITLE
Version 1.40 is misssing

### ISSUE THREAD

**Issue by steeren** [openui5/packaged-themelib_sap_belize#1]
Hi,
Is this an officially supported package? It remains at version 1.37 while all other packages have been tagged with the new 1.40 version.

**Comment by matz3** [comment]
Nope, this was due to a missing configuration on our side, sorry.
I've just pushed both 1.40 and 1.42 for this repo. Thanks for letting us know 👍

**Comment by steeren** [comment]
Great, thank you!!

**Comment by matz3** [comment]
I will disable the "Issues" functionality now as it is done for all other `packaged-` projects.
Please use the [SAP/openui5](https://github.com/SAP/openui5) repo to report any issues as suggested in the README.
